[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_hello_world = "GWTzAruVThiratXikUeYHo8F1ruZJQiVvfWczQRiwNX9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 30
shutdown_wait = 2000
upgradeable = false
